apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOakF4TURZeApOREl4TWpKYUZ3MDBOakF4TURZeE5ESXhNakphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEdHRwb2VrN3QvNFoxcmlyaitJWnB1dVFCbnJoQ3FxZTlGQjBSQkVYOGw2STVlWU9aRwppOHhKWUFSM0xuNXVtZnJxNVhPc2dkZmRRU2tWMEw5YWh1L3Q0WkFIQitKNmQ3T0lra0VkT2lNcyt2elhUcnU1CnV6TDVTVTZBWjU5TkhKVnBMeEpsMEZ5VkU3K1VCSEpkRkNvRlJVK2FhbUJYWTljUUVRcTZtRW5sR2hZQi9NbnIKd1phNGR2S0dXSWFGa3pkZU5BcGprN25mS082cHBsSHgzaXZ5Z0gyZ1hqS3Byc2lIcEkyUzN6ZmxCam4wQXYvcAp1WG9xanhtSi9uY0lMOVBXS0dNam1MMnA0YS9ESnVqOStwZXlIbHRzQmtpWFVqSEdKTFViZXBBeEZJUGVBN0VaCjRNZkhUNnNvZFB4L3pvNDFrSFpvNXZMUFpvMzh4UndkSXJIOUFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlN5QVN4YUdsZUNNcll5R0R2eQpqU0pYS3lKSi9EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvYXN6ci9nbUs4UUg5Vyt3M0xqRUJxTUdRWnhWCk9lcWVGTzFEZ1hKNjFaVWE1UnAxNWEzS2RwNTVDS0prQmlWd3kvNWUvNElmdHNJenNNMHlDbVdzNGgvZDhnckYKOWtHbUo0cjdKc0dDWnVmbmtGWVlXYlJiZ2s2WStRbmhJVlFESUhCaERpQnVEMlJxUWFrYTRwd3Q0eUZkclZQRworekFEWEZvZ0c1L3llSFNJWnFqdURySkZkaitubTRUSnVpejBDVUhGTU1OeXFML3lGc01EeDVOMDU2VGFBWjMrCldqckdJNW5vK1ZJZVREeGNHSW1VSUhISlV0MzU4d2ZJOWZ3U2pSbnFnOU81WGRBMTBpMEhOK0VXTzRDYWRVbFgKNXFsT0tjS2UrSWMrbHdHT0ZQSEd3QVRmUTRyR0FiVk9WWVN5dFU1dHYwRHVueStLYjdzanZxb1V1Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3d37012c-1ba0-4b8e-a473-8e2581f9431b.k8s.ondigitalocean.com
  name: do-nyc3-golojan-prod
contexts:
- context:
    cluster: do-nyc3-golojan-prod
    user: do-nyc3-golojan-prod-admin
  name: do-nyc3-golojan-prod
current-context: do-nyc3-golojan-prod
kind: Config
preferences: {}
users:
- name: do-nyc3-golojan-prod-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=golojan
      - 3d37012c-1ba0-4b8e-a473-8e2581f9431b
      command: C:\Program Files\doctl\doctl.exe
      env: null
      provideClusterInfo: false
