apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOakF4TURZdwpPVEkyTVRKYUZ3MDBOakF4TURZd09USTJNVEphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNHVCamJFVEF5a2Q3c3BUSitZaDNuSHV2SHM1dEdmUFg3T1Y5dk5tN25NK1VkN1UzYQpoT3Vkc1h3ZjlvdjMzYldOdUViNEFNcGZDWFMxOTYvVWVBbm9yaFlCNW1xS2l3STVlTnVUVlFYRU1PQmVnS3Z1Cmk2V1BHNnF6eTBrQnpkTmY5QTlEeHNKTWtrNDdvdUJadTZtamsycnMyV2JWOHBpN1FQTWxxaXZ4YnhzeWJISDkKSWs1RmFqdzBhUGN6SlhuU2w2a2V0Zlp2cTVPbHh0MFI4andjWm0wdmdGRHd6cWJ1ZjIyMzBTaXNDVVgzbkhhUwpJYm05b3F6VGFHRW9LbzR5RXltcFNzV0JTSU1VbGZTeFloTXJScWIyWDQ3RDlYOUgrZ3FSTzU1Wkt3TTM1RzZBClg2SWNrL1BVblFnbUtWcXU5MldZSmRNcEhNdW1MTC80RTB1bEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNOTEsrMWV0QTAwOXJEVWR5SApISmJQUk85Z2tqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFDek5nT3lIdFlmZWlITWJOeUNydUF5UmRPL3o3CkpUNktEWldnVnoyQkozeEJMclRHM0hwM1B0RkdaMzV3UTFYc0FDbmRzb29DTGpHUVdrVmRXMkdpZDU3SDI5dVAKaDVXVlVveDhMNm1BTys1a2UvamVjU1dDUFE1UkprN21TYzFpNnZkQUE3dm5FK0dDa2F5UGE0TFVFZUZGYXNkbgpvUnRJWTlqYmh0dEpKZVBHUWxQeEk0NGhSNFRjM1dFeUplbnRpSjFoNllBcmNZbHNvWHVMaStYMllldmJWMVZNCk91YWdDSXVXUW12aEtMbEZHRXJ3eWhvWS9ZanJ3S2QyRHNCK0VwbFlEaHY1RFh4Zm9Dem4xUDY1VFBVaDMrZm0KdzBpU1M3QTNkUHo2ZWpyVS9ST2gvOWpLaTRUaW5vZ2xtU1BmRzdJRGdSNlNIQ3NpUlUrRkgrenExUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://9f7bc72b-ffa8-4b55-91e7-5da295f38f12.k8s.ondigitalocean.com
    name: do-nyc3-golojan-prod
contexts:
  - context:
      cluster: do-nyc3-golojan-prod
      user: do-nyc3-golojan-prod-admin
    name: do-nyc3-golojan-prod
current-context: do-nyc3-golojan-prod
users:
  - name: do-nyc3-golojan-prod-admin
    user:
      token: dop_v1_5ed2ab4576dc14c48cfedd1e8346c826b0a99d4a644557b2a23f1ab36e1d27fb
